### ISSUE TITLE
Групируй код

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/towerDefense#6]
Не нужно пихать всё в 1 папку

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/towerDefense/commit/0f4872b23934453eee4694967e763d2a3c341637. Может быть вы можете посоветовать какие-нибудь статьи/источники о том, как это делать правильно?

**Comment by Red-Cat-Fat** [comment]
Просто разделяй на логические элементы. 
В коммите ты только удалил файлы. Зачем?

**Comment by maxPow1776** [comment]
Вот https://github.com/maxPow1776/towerDefense/commit/4fa62957c24f5fcb11b3121869287a42e56eb01b. Я случайно
